### ISSUE TITLE
plugin is breaking WP

### ISSUE THREAD

**Issue by jonaswebdev** [iamsayan/migrate-wp-cron-to-action-scheduler#3]
HI,

I got an error message that broke my WP and after email with these details below. I disabled this plugin to my WP back to work.

```
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.8.2
Current theme: Kicker Child (version 1.0)
Current plugin: Migrate WP Cron to Action Scheduler (version 1.0.3)
PHP version 7.4.3



Error Details
=============
An error of type E_ERROR was caused in line 272 of the file /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/vendor/woocommerce/action-scheduler/functions.php. Error message: Uncaught Exception: DateTime::__construct(): Failed to parse time string (1) at position 0 (1): Unexpected character in /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/vendor/woocommerce/action-scheduler/functions.php:272
Stack trace:
#0 /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/vendor/woocommerce/action-scheduler/functions.php(272): DateTime->__construct()
#1 /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/vendor/woocommerce/action-scheduler/functions.php(226): as_get_datetime_object()
#2 /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/includes/Helpers/HelperFunctions.php(110): as_get_scheduled_actions()
#3 /...my-domain-file-path.../public_html/wp-content/plugins/migrate-wp-cron-to-action-scheduler/includes/Core/Connection.php(284): Mwpcac\Core\Connection->get_next_action_by_data()
#4 /...my-domain-file-path.../public_html/wp-includ
```

I tried to debug to get the Data input that caused it, but no success...

**Comment by iamsayan** [comment]
Hi @jonaswebdev 

Thanks for let me know.

Please download the v1.0.4 version of the plugin from GitHub Repo and let me know if problem still exists.

**Comment by jonaswebdev** [comment]
Hi @iamsayan  thank you so much for the update!
I installed the new plugin version and it's running well, for now...
I will let you know if I experienced any issues, good job :)
